
[project]
name = "core-contracts"

[repl]
costs_version = 1

[contracts.bns]
path = "../../stackslib/src/chainstate/stacks/boot/bns.clar"
depends_on = []

# pox-4 contains concat of boot/pox-4 and boot/pox-testnet
# path = "../../stackslib/src/chainstate/stacks/boot/pox-4.clar"
# path = "../../stackslib/src/chainstate/stacks/boot/pox-testnet.clar"
[contracts.pox-4]
path = "./contracts/pox/pox-4.clar"
depends_on = []
clarity = 2
epoch = 2.4

[contracts.pox-helper]
path = "./contracts/pox/pox-helper.clar"
depends_on = []
clarity = 2
epoch = 2.4
